import { ITheme } from '~/interfaces';
import { BLUE_500 } from './colors';

export const skyeLight: ITheme = {
  'titlebar.backgroundColor': '#fff',
  'addressbar.backgroundColor': '#F2F8FF',
  'addressbar.textColor': '#000',
  'toolbar.backgroundColor': '#F2F8FF',
  'toolbar.bottomLine.backgroundColor': 'rgba(0, 0, 0, 0.12)',
  'toolbar.lightForeground': false,
  'toolbar.separator.color': 'rgba(0, 0, 0, 0.12)',
  'tab.selected.textColor': '#000',
  'tab.selected.backgroundColor': '#E5F1FF',
  'tab.backgroundColor': '#F2F8FF',
  'tab.textColor': `rgba(0, 0, 0, 0.7)`,
  'control.backgroundColor': '#F2F8FF',
  'control.hover.backgroundColor': 'rgba(0, 0, 0, 0.1)',
  'control.valueColor': '#000',
  'control.lightIcon': false,
  'control.borderBottomColor': '#E5F1FF',
  'button.backgroundColor': '#1E6FEB',
  'switch.backgroundColor': 'rgba(0, 0, 0, 0.16)',
  'dialog.backgroundColor': '#fff',
  'dialog.separator.color': 'rgba(0, 0, 0, 0.12)',
  'dialog.textColor': '#000',
  'dialog.lightForeground': false,
  'searchBox.backgroundColor': '#F7FBFF',
  'searchBox.lightForeground': false,
  'pages.backgroundColor': '#fff',
  'pages.lightForeground': false,
  'pages.textColor': '#000',
  'dropdown.backgroundColor': '#fff',
  'dropdown.backgroundColor.translucent': 'rgba(255, 255, 255, 0.7)',
  'dropdown.separator.color': 'rgba(0, 0, 0, 0.12)',
  'pages.navigationDrawer1.backgroundColor': '#E5F1FF',
  'pages.navigationDrawer2.backgroundColor': '#F2F8FF',
  'pages.navigationDrawer2.searchBar.backgroundColor': '#ffffff',
  accentColor: '#fff',
  backgroundColor: '#fff',
};

export const skyeDark: ITheme = {
  'titlebar.backgroundColor': '#070B10',
  'addressbar.backgroundColor': '#1A1E2C',
  'addressbar.textColor': '#fff',
  'toolbar.backgroundColor': '#1A1E2C',
  'toolbar.bottomLine.backgroundColor': 'rgba(255, 255, 255, 0.08)',
  'toolbar.lightForeground': true,
  'toolbar.separator.color': 'rgba(255, 255, 255, 0.12)',
  'tab.selected.textColor': '#fff',
  'tab.textColor': 'rgba(255, 255, 255, 0.54)',

  'tab.selected.backgroundColor': '#1A1E2C',
  'tab.backgroundColor': '#11151A',

  'control.backgroundColor': '#11151A',
  'control.hover.backgroundColor': 'rgba(255, 255, 255, 0.12)',
  'control.valueColor': '#fff',
  'control.lightIcon': true,
  'control.borderBottomColor': '#10121a',
  'button.backgroundColor': '#1E6FEB',
  'switch.backgroundColor': 'rgba(255, 255, 255, 0.24)',
  'dialog.backgroundColor': '#1A1E2C',
  'dialog.separator.color': 'rgba(255, 255, 255, 0.12)',
  'dialog.textColor': '#fff',
  'dialog.lightForeground': true,
  'searchBox.backgroundColor': '#070B10',
  'searchBox.lightForeground': true,
  'pages.backgroundColor': '#1A1E2C',
  'pages.lightForeground': true,
  'pages.textColor': '#fff',
  'dropdown.backgroundColor': '#1A1E2C',
  'dropdown.backgroundColor.translucent': 'rgb(60, 60, 60, 0.6)',
  'dropdown.separator.color': 'rgba(255, 255, 255, 0.12)',
  'pages.navigationDrawer1.backgroundColor': '#12151f',
  'pages.navigationDrawer2.backgroundColor': '#10121a',
  'pages.navigationDrawer2.searchBar.backgroundColor': '#000000',
  backgroundColor: '#070B10',
  accentColor: '#1A1E2C',
};
